-- Esquema base del catálogo.
--
-- Corrige los defectos estructurales del modelo de 2023. El más grave: cinco
-- @OneToMany sin `mappedBy` hacían que Hibernate generara una tabla intermedia
-- ADEMÁS de la columna FK del @ManyToOne correspondiente. Cada asociación se
-- guardaba por duplicado (country_restaurants + restaurant.country_id, etc.) y
-- las dos copias las mantenían servicios distintos, así que divergían.
--
-- Aquí sólo hay tabla intermedia donde la relación es de verdad muchos-a-muchos:
-- cultura<->país y receta<->restaurante. Todo lo demás es una FK y nada más.

-- ---------------------------------------------------------------- columnas --
-- Todas las tablas llevan el mismo bloque de auditoría y versionado. Se repite
-- de forma explícita en cada CREATE TABLE en vez de heredarlo: la herencia de
-- tablas de Postgres no propaga índices ni constraints y complica los backups.

CREATE TABLE gastronomic_culture (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120)  NOT NULL,
    slug        VARCHAR(140)  NOT NULL,
    description VARCHAR(2000),
    image_url   VARCHAR(1000),

    version     BIGINT        NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    created_by  VARCHAR(64),
    updated_by  VARCHAR(64),

    CONSTRAINT uq_culture_name UNIQUE (name),
    CONSTRAINT uq_culture_slug UNIQUE (slug)
);

CREATE TABLE country (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    -- ISO 3166-1. En los datos de 2023 Japón estaba como 'JA', que no es un
    -- código válido; el correcto es 'JP'. El CHECK impide que vuelva a pasar.
    --
    -- VARCHAR y no CHAR: CHAR en Postgres es bpchar, que rellena con espacios
    -- hasta la longitud fija, así que 'JP ' y 'JP' dejan de ser intercambiables
    -- según el contexto de comparación. La longitud ya la garantiza el CHECK.
    iso2       VARCHAR(2)   NOT NULL,
    iso3       VARCHAR(3),

    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),

    CONSTRAINT uq_country_name UNIQUE (name),
    CONSTRAINT uq_country_iso2 UNIQUE (iso2),
    CONSTRAINT ck_country_iso2_format CHECK (iso2 ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_country_iso3_format CHECK (iso3 IS NULL OR iso3 ~ '^[A-Z]{3}$')
);

-- Muchos-a-muchos legítimo: una cultura abarca varios países y un país puede
-- albergar varias culturas. Este SÍ merece tabla intermedia.
CREATE TABLE culture_country (
    culture_id BIGINT NOT NULL REFERENCES gastronomic_culture (id) ON DELETE CASCADE,
    country_id BIGINT NOT NULL REFERENCES country (id)             ON DELETE CASCADE,
    PRIMARY KEY (culture_id, country_id)
);

CREATE TABLE gastronomic_category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    image_url  VARCHAR(1000),
    -- ON DELETE CASCADE va hacia ABAJO: borrar una cultura borra sus categorías.
    -- En 2023 la entidad tenía @ManyToOne(cascade = REMOVE) hacia el padre, o
    -- sea que borrar UNA categoría intentaba borrar la cultura entera y, por
    -- sus propias cascadas, todas las recetas y demás categorías de esa cultura.
    culture_id BIGINT       NOT NULL REFERENCES gastronomic_culture (id) ON DELETE CASCADE,

    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),

    -- El nombre sólo es único DENTRO de una cultura: "Postres" puede existir en
    -- la cocina italiana y en la japonesa. El servicio de 2023 buscaba por
    -- nombre global, así que crear "Postres" en italiana devolvía la japonesa.
    CONSTRAINT uq_category_name_culture UNIQUE (name, culture_id)
);

CREATE TABLE representative_product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    brand       VARCHAR(120) NOT NULL,
    category_id BIGINT       NOT NULL REFERENCES gastronomic_category (id) ON DELETE CASCADE,

    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    created_by  VARCHAR(64),
    updated_by  VARCHAR(64),

    CONSTRAINT uq_product_name_brand UNIQUE (name, brand)
);

CREATE TABLE recipe (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(160) NOT NULL,
    slug              VARCHAR(180) NOT NULL,
    description       VARCHAR(2000),
    culture_id        BIGINT       NOT NULL REFERENCES gastronomic_culture (id) ON DELETE CASCADE,

    -- Enriquecimiento respecto a 2023.
    prep_time_minutes INTEGER,
    servings          SMALLINT,
    difficulty        VARCHAR(16),

    version           BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ,
    created_by        VARCHAR(64),
    updated_by        VARCHAR(64),

    CONSTRAINT uq_recipe_name_culture UNIQUE (name, culture_id),
    CONSTRAINT uq_recipe_slug         UNIQUE (slug),
    CONSTRAINT ck_recipe_difficulty   CHECK (difficulty IS NULL OR difficulty IN ('FACIL', 'MEDIA', 'DIFICIL')),
    CONSTRAINT ck_recipe_prep_time    CHECK (prep_time_minutes IS NULL OR prep_time_minutes > 0),
    CONSTRAINT ck_recipe_servings     CHECK (servings IS NULL OR servings > 0)
);

-- El UML de 2023 modelaba Step como entidad de primera clase; el código lo
-- colapsó en un único `@Lob String instructions` de ~1500 caracteres que se
-- cargaba entero en cada listado. Recuperarlo como tabla permite el modo cocina
-- paso a paso y no arrastra el texto completo en las consultas de listado.
CREATE TABLE recipe_step (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id   BIGINT       NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    position    SMALLINT     NOT NULL,
    instruction TEXT         NOT NULL,
    -- Duración detectada en el texto ("cocer 20-25 minutos"), usada por los
    -- temporizadores del modo cocina. Null si el paso no menciona tiempo.
    duration_seconds INTEGER,

    CONSTRAINT uq_step_recipe_position UNIQUE (recipe_id, position),
    CONSTRAINT ck_step_position        CHECK (position > 0),
    CONSTRAINT ck_step_duration        CHECK (duration_seconds IS NULL OR duration_seconds > 0)
);

CREATE TABLE ingredient (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT       NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    position  SMALLINT     NOT NULL,
    name      VARCHAR(160) NOT NULL,
    quantity  NUMERIC(10, 2),
    unit      VARCHAR(32),

    CONSTRAINT uq_ingredient_recipe_position UNIQUE (recipe_id, position),
    CONSTRAINT ck_ingredient_quantity        CHECK (quantity IS NULL OR quantity > 0)
);

CREATE TABLE dish_multimedia (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id  BIGINT        NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    url        VARCHAR(1000) NOT NULL,
    position   SMALLINT      NOT NULL DEFAULT 1,
    -- Poblados por el verificador de enlaces (Fase 5). Los datos originales
    -- traen URLs muertas y una malformada literal: 'https:https://...'.
    last_checked_at TIMESTAMPTZ,
    last_status     SMALLINT,

    version    BIGINT        NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),

    CONSTRAINT uq_multimedia_url UNIQUE (url)
);

CREATE TABLE restaurant (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(160) NOT NULL,
    city       VARCHAR(120) NOT NULL,
    contact    VARCHAR(200),
    country_id BIGINT       NOT NULL REFERENCES country (id) ON DELETE RESTRICT,

    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),

    CONSTRAINT uq_restaurant_name_city_country UNIQUE (name, city, country_id)
);

-- Segundo muchos-a-muchos legítimo: un restaurante sirve varias recetas y una
-- receta se sirve en varios restaurantes.
CREATE TABLE recipe_restaurant (
    recipe_id     BIGINT NOT NULL REFERENCES recipe (id)     ON DELETE CASCADE,
    restaurant_id BIGINT NOT NULL REFERENCES restaurant (id) ON DELETE CASCADE,
    PRIMARY KEY (recipe_id, restaurant_id)
);

CREATE TABLE michelin_star (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT      NOT NULL REFERENCES restaurant (id) ON DELETE CASCADE,
    acquired      DATE        NOT NULL,

    version       BIGINT      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ,
    created_by    VARCHAR(64),
    updated_by    VARCHAR(64),

    -- Un restaurante no puede recibir dos estrellas el mismo día.
    CONSTRAINT uq_star_restaurant_date UNIQUE (restaurant_id, acquired),
    CONSTRAINT ck_star_not_future      CHECK (acquired <= CURRENT_DATE)
);

-- El UML de 2023 especificaba MichelinStar 0..3 por restaurante y el código no
-- lo comprobaba en ningún sitio. No se puede expresar como CHECK porque la
-- regla cruza filas, así que va como trigger: en la base de datos, no en un
-- servicio, para que ninguna ruta de escritura pueda saltárselo.
CREATE OR REPLACE FUNCTION enforce_michelin_star_limit() RETURNS TRIGGER AS $$
DECLARE
    star_count INTEGER;
BEGIN
    SELECT count(*) INTO star_count
    FROM michelin_star
    WHERE restaurant_id = NEW.restaurant_id;

    IF star_count > 3 THEN
        RAISE EXCEPTION
            'El restaurante % ya tiene el maximo de 3 estrellas Michelin', NEW.restaurant_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- CONSTRAINT TRIGGER diferido: se evalúa al hacer COMMIT, no fila a fila, así
-- que insertar tres estrellas en una misma transacción funciona sin depender
-- del orden de las filas.
CREATE CONSTRAINT TRIGGER trg_michelin_star_limit
    AFTER INSERT OR UPDATE ON michelin_star
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
EXECUTE FUNCTION enforce_michelin_star_limit();

-- ----------------------------------------------------------------- índices --
-- Postgres indexa automáticamente las PK y las columnas UNIQUE, pero NO las
-- claves foráneas. Sin estos índices cada borrado del padre hace un seq scan
-- del hijo para validar la FK, y los listados filtrados por padre también.

CREATE INDEX idx_category_culture      ON gastronomic_category (culture_id);
CREATE INDEX idx_product_category      ON representative_product (category_id);
CREATE INDEX idx_recipe_culture        ON recipe (culture_id);
CREATE INDEX idx_step_recipe           ON recipe_step (recipe_id);
CREATE INDEX idx_ingredient_recipe     ON ingredient (recipe_id);
CREATE INDEX idx_multimedia_recipe     ON dish_multimedia (recipe_id);
CREATE INDEX idx_restaurant_country    ON restaurant (country_id);
CREATE INDEX idx_star_restaurant       ON michelin_star (restaurant_id);
CREATE INDEX idx_culture_country_rev   ON culture_country (country_id);
CREATE INDEX idx_recipe_restaurant_rev ON recipe_restaurant (restaurant_id);
