-- Datos de ejemplo, portados desde sql/data.sql del proyecto de 2023.
--
-- En el original ese archivo vivía bajo sql/ y NO en el classpath, así que
-- Spring Boot nunca lo ejecutaba: había que pegarlo a mano en la consola de
-- H2. Aquí es una migración de Flyway, de modo que el estado inicial es
-- reproducible y el test end-to-end puede afirmar sobre datos concretos.
--
-- Los ids son explícitos a propósito (la PK es GENERATED BY DEFAULT, no
-- ALWAYS): el test end-to-end necesita poder apuntar a filas conocidas. Las
-- secuencias se reajustan al final.

-- ------------------------------------------------------------------ países --
-- Japón figuraba como 'JA' en los datos de 2023, que no es un código ISO
-- 3166-1 válido. El correcto es 'JP', y ahora el CHECK de la tabla impide
-- que se vuelva a colar.
INSERT INTO country (id, name, iso2, iso3) VALUES
    (1, 'Italia',   'IT', 'ITA'),
    (2, 'México',   'MX', 'MEX'),
    (3, 'Japón',    'JP', 'JPN'),
    (4, 'India',    'IN', 'IND'),
    (5, 'Colombia', 'CO', 'COL');

-- --------------------------------------------------------------- culturas --
INSERT INTO gastronomic_culture (id, name, slug, description) VALUES
    (1, 'Cocina italiana',   'cocina-italiana',   'Platos y sabores tradicionales de Italia, construidos sobre pocos ingredientes de buena calidad.'),
    (2, 'Cocina mexicana',   'cocina-mexicana',   'Cocina picante y llena de matices, con el maíz y el chile como columna vertebral.'),
    (3, 'Cocina japonesa',   'cocina-japonesa',   'Platos delicados donde manda la estacionalidad y la calidad del producto crudo.'),
    (4, 'Cocina india',      'cocina-india',      'Cocina rica y aromática, definida por el uso en capas de las especias.'),
    (5, 'Cocina colombiana', 'cocina-colombiana', 'Cocina tropical y contundente, con fuerte variación entre regiones.');

INSERT INTO culture_country (culture_id, country_id) VALUES
    (1, 1), (2, 2), (3, 3), (4, 4), (5, 5);

-- -------------------------------------------------------------- categorías --
INSERT INTO gastronomic_category (id, name, culture_id) VALUES
    (1, 'Entradas',        1),
    (2, 'Platos fuertes',  2),
    (3, 'Postres',         3),
    (4, 'Comida callejera', 5),
    (5, 'Bebidas',         5);

-- Demuestra que el nombre es único POR CULTURA y no globalmente: el servicio
-- de 2023 buscaba por nombre global, así que crear "Postres" en la cocina
-- italiana devolvía la de la japonesa.
INSERT INTO gastronomic_category (id, name, culture_id) VALUES
    (6, 'Postres', 1);

-- ---------------------------------------------------------------- productos --
INSERT INTO representative_product (id, name, brand, category_id) VALUES
    (1, 'Queso parmesano', 'Galbani',   1),
    (2, 'Aceite de oliva', 'Bertolli',  1),
    (3, 'Salchicha',       'Zenú',      4),
    (4, 'Café',            'Juan Valdez', 5),
    (5, 'Chocolate',       'Lindt',     3);

-- ------------------------------------------------------------- restaurantes --
INSERT INTO restaurant (id, name, city, contact, country_id) VALUES
    (1, 'La Taquería',    'Monterrey', 'info@lataqueria.mx',     2),
    (2, 'La Pizzeria',    'Roma',      'info@lapizzeria.it',     1),
    (3, 'Sushi Paradise', 'Tokio',     'info@sushiparadise.jp',  3),
    (4, 'Curry House',    'Bombay',    'info@curryhouse.in',     4),
    (5, 'Andrés',         'Bogotá',    'info@andres.co',         5);

-- Un restaurante con las tres estrellas permitidas: es la fixture con la que
-- el test end-to-end comprueba que la cuarta se rechaza. La regla 0..3 estaba
-- en el UML de 2023 y no se validaba en ningún sitio.
INSERT INTO michelin_star (id, restaurant_id, acquired) VALUES
    (1, 3, DATE '2021-02-10'),
    (2, 3, DATE '2022-02-14'),
    (3, 3, DATE '2023-02-13'),
    (4, 2, DATE '2021-08-27'),
    (5, 4, DATE '2022-11-05');

-- ----------------------------------------------------------------- recetas --
-- Corrección de datos: en 2023 'Tacos al Pastor' apuntaba a culture_id 1
-- (cocina italiana) y 'Pasta Carbonara' a culture_id 2 (cocina mexicana).
-- Estaban intercambiadas. Como el texto de las recetas está en inglés y la
-- interfaz en español, este corpus es además el caso de prueba real del
-- modelo de embeddings multilingüe de la Fase 4.
INSERT INTO recipe (id, name, slug, description, culture_id, prep_time_minutes, servings, difficulty) VALUES
    (1, 'Tacos al Pastor', 'tacos-al-pastor', 'Cerdo marinado en achiote, servido en tortilla de maíz con piña.',        2, 150, 4, 'MEDIA'),
    (2, 'Pasta Carbonara', 'pasta-carbonara', 'Pasta romana con huevo, queso curado y guanciale. Sin nata.',             1,  25, 2, 'FACIL'),
    (3, 'Sushi Rolls',     'sushi-rolls',     'Rollos de arroz avinagrado y alga nori con relleno variable.',            3,  60, 4, 'DIFICIL'),
    (4, 'Chicken Curry',   'chicken-curry',   'Pollo guisado en leche de coco con una base de especias tostadas.',       4,  45, 4, 'FACIL'),
    (5, 'Bandeja Paisa',   'bandeja-paisa',   'Plato antioqueño abundante: frijoles, arroz, carnes, plátano y huevo.',   5,  90, 2, 'MEDIA');

-- Los pasos vuelven a ser filas, como en el UML original. En 2023 esto era un
-- único @Lob de ~1500 caracteres que se cargaba entero en cada listado.
-- duration_seconds sólo se rellena cuando el texto menciona un tiempo; es lo
-- que alimenta los temporizadores del modo cocina.
INSERT INTO recipe_step (recipe_id, position, instruction, duration_seconds) VALUES
    (1, 1, 'Mezclar la pasta de achiote, el vinagre blanco, el aceite, el orégano seco, el comino, el pimentón ahumado, la sal, la pimienta negra y el ajo picado hasta formar una marinada homogénea.', NULL),
    (1, 2, 'Añadir el cerdo en lonchas finas y remover hasta cubrirlo por completo. Tapar y refrigerar al menos 2 horas, mejor toda la noche.', 7200),
    (1, 3, 'Calentar la plancha a fuego medio-alto y engrasarla ligeramente.', NULL),
    (1, 4, 'Ensartar el cerdo en brochetas y asar de 10 a 12 minutos, girando de vez en cuando, hasta que esté hecho y ligeramente tostado. Pincelar con zumo de piña mientras se asa.', 660),
    (1, 5, 'Retirar de las brochetas, dejar reposar unos minutos y cortar en tiras finas.', NULL),
    (1, 6, 'Calentar las tortillas de maíz en un comal. Servir el cerdo encima con cebolla, cilantro y piña, y terminar con lima exprimida.', NULL),

    (2, 1, 'Cocer la pasta en abundante agua con sal hasta que esté al dente. Reservar media taza del agua de cocción antes de escurrir.', NULL),
    (2, 2, 'Mientras tanto, dorar el guanciale en una sartén amplia a fuego medio hasta que suelte su grasa y quede crujiente, unos 5 a 7 minutos.', 360),
    (2, 3, 'Batir los huevos con el parmesano y el pecorino rallados. Salpimentar.', NULL),
    (2, 4, 'Retirar la sartén del fuego y dejar que baje de temperatura unos segundos. Añadir la pasta escurrida y remover para que se impregne de la grasa.', NULL),
    (2, 5, 'Verter la mezcla de huevo y queso removiendo rápido: el calor residual la cuaja en una crema. Si espesa demasiado, aflojar con el agua de cocción reservada.', NULL),
    (2, 6, 'Servir de inmediato, con pimienta negra recién molida.', NULL),

    (3, 1, 'Lavar el arroz para sushi hasta que el agua salga clara y cocerlo según las instrucciones del paquete.', NULL),
    (3, 2, 'Pasar el arroz a un bol amplio y, todavía templado, mezclarlo con el vinagre de sushi con movimientos suaves. Dejar enfriar por completo.', NULL),
    (3, 3, 'Cortar los rellenos en tiras largas y finas: pepino, aguacate, salmón ahumado o atún.', NULL),
    (3, 4, 'Colocar una lámina de nori sobre la esterilla y extender el arroz dejando unos dos centímetros libres en el borde superior.', NULL),
    (3, 5, 'Disponer el relleno en línea sobre el arroz y enrollar con la esterilla apretando de forma uniforme. Sellar el borde con un poco de agua.', NULL),
    (3, 6, 'Cortar cada rollo en porciones con un cuchillo afilado, mojándolo entre corte y corte. Servir con soja, wasabi y jengibre encurtido.', NULL),

    (4, 1, 'Calentar el aceite en una sartén amplia y pochar la cebolla picada hasta que esté blanda y dorada, unos 5 minutos.', 300),
    (4, 2, 'Añadir el ajo y el jengibre rallado y sofreír 1 o 2 minutos más, hasta que suelten aroma.', 90),
    (4, 3, 'Incorporar la mezcla de especias (curry, comino, cilantro molido, cúrcuma y cayena) y remover para que se tueste y cubra el sofrito.', NULL),
    (4, 4, 'Añadir el pollo troceado y sellarlo por todos lados, de 5 a 7 minutos.', 360),
    (4, 5, 'Verter la leche de coco, el caldo, el concentrado de tomate y un punto de azúcar moreno. Remover para integrar.', NULL),
    (4, 6, 'Llevar a ebullición suave, bajar el fuego y cocer tapado de 20 a 25 minutos, hasta que el pollo esté tierno. Rectificar de sal y servir con arroz.', 1350),

    (5, 1, 'Cocer por separado el arroz blanco y los frijoles rojos según sus instrucciones.', NULL),
    (5, 2, 'Freír el tocino en una sartén amplia hasta que esté crujiente y reservarlo.', NULL),
    (5, 3, 'En la misma sartén, cocinar la carne molida y el chorizo hasta que estén bien hechos. Reservar.', NULL),
    (5, 4, 'Freír las tajadas de plátano maduro en aceite caliente hasta que se doren.', NULL),
    (5, 5, 'Freír los huevos al gusto, normalmente con la yema líquida.', NULL),
    (5, 6, 'Montar la bandeja: arroz, frijoles, tocino, carne, chorizo, plátano, huevo, aguacate y arepa. Napar con hogao y servir de inmediato.', NULL);

INSERT INTO ingredient (recipe_id, position, name, quantity, unit) VALUES
    (2, 1, 'Espaguetis',          200, 'g'),
    (2, 2, 'Guanciale',           100, 'g'),
    (2, 3, 'Huevo',                 2, 'unidad'),
    (2, 4, 'Pecorino romano',      50, 'g'),
    (2, 5, 'Pimienta negra',     NULL, 'al gusto'),
    (4, 1, 'Pechuga de pollo',    600, 'g'),
    (4, 2, 'Leche de coco',       400, 'ml'),
    (4, 3, 'Cebolla',               1, 'unidad'),
    (4, 4, 'Curry en polvo',        2, 'cucharada'),
    (4, 5, 'Jengibre fresco',      15, 'g');

-- ------------------------------------------------------------------ imágenes --
-- La última URL está deliberadamente malformada ('https:https://...'): viene
-- tal cual de los datos de 2023 y se conserva como fixture del verificador de
-- enlaces de la Fase 5, que debe detectarla. No es una errata de este archivo.
INSERT INTO dish_multimedia (id, recipe_id, url, position) VALUES
    (1, 1, 'https://www.seriouseats.com/thmb/4kbwN13BlZnZ3EywrtG2AzCKuYs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210712-tacos-al-pastor-melissa-hom-seriouseats-37-f72cdd02c9574bceb1eef1c8a23b76ed.jpg', 1),
    (2, 1, 'https://chefcompass.com/wp-content/uploads/pastor_tacos.jpg', 2),
    (3, 2, 'https://www.thespruceeats.com/thmb/ovIQQQxQajADuIE2lqhgqq7ppyE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/pasta-carbonara-recipe-5210168-hero-01-80090e56abc04ca19d88ebf7fad1d157.jpg', 1),
    (4, 3, 'https://ichisushi.com/wp-content/uploads/2022/05/Best-Hawaiian-Roll-Sushi-Recipes.jpg', 1),
    (5, 5, 'https://cdn.colombia.com/gastronomia/2011/08/02/bandeja-paisa-1616.gif', 1),
    (6, 4, 'https:https://www.allrecipes.com/thmb/FL-xnyAllLyHcKdkjUZkotVlHR8=/1500x0/indian-chicken-curry.jpg', 1);

-- ------------------------------------------------------- recetas y restaurantes --
INSERT INTO recipe_restaurant (recipe_id, restaurant_id) VALUES
    (1, 1), (2, 2), (3, 3), (4, 4), (5, 5);

-- ------------------------------------------------------------------ secuencias --
-- Se insertaron ids explícitos, así que hay que adelantar las secuencias de
-- identidad o el primer INSERT de la aplicación chocaría con una PK existente.
SELECT setval(pg_get_serial_sequence('country', 'id'),                (SELECT max(id) FROM country));
SELECT setval(pg_get_serial_sequence('gastronomic_culture', 'id'),    (SELECT max(id) FROM gastronomic_culture));
SELECT setval(pg_get_serial_sequence('gastronomic_category', 'id'),   (SELECT max(id) FROM gastronomic_category));
SELECT setval(pg_get_serial_sequence('representative_product', 'id'), (SELECT max(id) FROM representative_product));
SELECT setval(pg_get_serial_sequence('restaurant', 'id'),             (SELECT max(id) FROM restaurant));
SELECT setval(pg_get_serial_sequence('michelin_star', 'id'),          (SELECT max(id) FROM michelin_star));
SELECT setval(pg_get_serial_sequence('recipe', 'id'),                 (SELECT max(id) FROM recipe));
SELECT setval(pg_get_serial_sequence('dish_multimedia', 'id'),        (SELECT max(id) FROM dish_multimedia));
SELECT setval(pg_get_serial_sequence('recipe_step', 'id'),            (SELECT max(id) FROM recipe_step));
SELECT setval(pg_get_serial_sequence('ingredient', 'id'),             (SELECT max(id) FROM ingredient));
