-- Identidad y funciones sociales.
--
-- El registro es instantáneo y sin verificación de correo, por decisión de
-- diseño: este proyecto se enseña, y la fricción de registro no aporta nada a
-- lo que demuestra. La autorización sí es real — cada quien sólo puede editar
-- y borrar lo suyo, y eso se comprueba en el servidor, no ocultando botones.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(40)  NOT NULL,
    email         VARCHAR(160),
    display_name  VARCHAR(80)  NOT NULL,
    -- BCrypt produce siempre 60 caracteres. Se dimensiona a 100 para no tener
    -- que migrar si algún día se cambia a Argon2, que es más largo.
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(16)  NOT NULL DEFAULT 'USER',

    version    BIGINT      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),

    CONSTRAINT uq_user_username  UNIQUE (username),
    CONSTRAINT uq_user_email     UNIQUE (email),
    CONSTRAINT ck_user_role      CHECK (role IN ('USER', 'ADMIN')),
    -- El nombre de usuario entra en URLs de perfil público, así que se acota a
    -- un alfabeto seguro en lugar de escaparlo en cada punto de uso.
    CONSTRAINT ck_user_username  CHECK (username ~ '^[a-z0-9][a-z0-9_.-]{2,39}$')
);

-- Valoraciones de recetas.
CREATE TABLE rating (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id  BIGINT      NOT NULL REFERENCES recipe (id)   ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    score      SMALLINT    NOT NULL,
    comment    VARCHAR(2000),

    version    BIGINT      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),

    -- Una valoración por persona y receta. Es la restricción la que lo
    -- garantiza, no una comprobación previa en el servicio: entre el SELECT y
    -- el INSERT cabe otra petición.
    CONSTRAINT uq_rating_user_recipe UNIQUE (user_id, recipe_id),
    CONSTRAINT ck_rating_score       CHECK (score BETWEEN 1 AND 5)
);

-- Agregados desnormalizados sobre la receta para poder ordenar por valoración
-- sin un GROUP BY en cada listado. Los mantiene un trigger, no la aplicación:
-- así no pueden quedar desfasados por una ruta de escritura que se olvide.
ALTER TABLE recipe
    ADD COLUMN rating_average NUMERIC(3, 2) NOT NULL DEFAULT 0,
    ADD COLUMN rating_count   INTEGER       NOT NULL DEFAULT 0;

CREATE OR REPLACE FUNCTION refresh_recipe_rating() RETURNS TRIGGER AS $$
DECLARE
    target_recipe BIGINT := COALESCE(NEW.recipe_id, OLD.recipe_id);
BEGIN
    UPDATE recipe r
       SET rating_count   = stats.total,
           rating_average = COALESCE(stats.average, 0)
      FROM (SELECT count(1) AS total, avg(score) AS average
              FROM rating WHERE recipe_id = target_recipe) AS stats
     WHERE r.id = target_recipe;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_rating_refresh
    AFTER INSERT OR UPDATE OR DELETE ON rating
    FOR EACH ROW
EXECUTE FUNCTION refresh_recipe_rating();

-- Favoritos. Polimórfico a propósito: guardar receta, restaurante y cultura en
-- tres tablas idénticas no aportaría nada, y el tipo va acotado por CHECK.
CREATE TABLE favorite (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    target_type VARCHAR(16) NOT NULL,
    target_id   BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_favorite UNIQUE (user_id, target_type, target_id),
    CONSTRAINT ck_favorite_type CHECK (target_type IN ('RECIPE', 'RESTAURANT', 'CULTURE'))
);

CREATE INDEX idx_rating_recipe    ON rating (recipe_id);
CREATE INDEX idx_rating_user      ON rating (user_id);
CREATE INDEX idx_favorite_user    ON favorite (user_id);
CREATE INDEX idx_recipe_rating    ON recipe (rating_average DESC, rating_count DESC);

-- Usuario administrador de la demostración. El hash es BCrypt de 'demo1234',
-- generado con coste 10.
--
-- Que una credencial conocida esté en el repositorio es deliberado y sólo
-- admisible porque este proyecto es una demostración local sin datos reales:
-- quien lo clone puede entrar sin configurar nada. En cualquier despliegue
-- real esta fila no debería existir.
INSERT INTO app_user (id, username, email, display_name, password_hash, role) VALUES
    (1, 'demo', 'demo@culturas.local', 'Cuenta de demostración',
     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN');

SELECT setval(pg_get_serial_sequence('app_user', 'id'), (SELECT max(id) FROM app_user));
